# Navigation Links
main:
  - name: Bio
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  # - name: Projects
  #   url: /#projects
  #   weight: 40
  - name: Teaching
    url: /#teaching
    weight: 50
  - name: Awards
    url: /#awards
    weight: 60
  - name: Moments
    url: /#moments
    weight: 65
  - name: Contact
    url: /#collaboration
    weight: 70
