# Navigation Links
main:
  - name: About
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: Research
    url: /#research
    weight: 30
  - name: Projects
    url: /#projects
    weight: 40
  - name: Teaching
    url: /#teaching
    weight: 50
  - name: Awards
    url: /#awards
    weight: 60
  - name: Skills
    url: /#skills
    weight: 70